### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Joe118** [Grevor/Viking.Pipeline#6]
Hi Grevor, do you have a roadmap for this project? Thanks!

**Comment by Grevor** [comment]
Hello Joe,

This is sort of a kata/rage-project of mine.
I had hoped to release it somewhere in the beginning of the year, but I've
failed to find time for it. I do worry about the low level of large-scale
testing, but maybe the only way to truly test it is to get it into people's
hands.

As for the roadmap, I think a March release for Viking.Pipeline is within
reach. The core is stable (and has been since december). There needs to be
more documentation and getting-started guides.
I also plan to make a Nuget for the Wpf project as well. It needs some
testing before going live.

As for the future of the project, I do not know. I want to see what people
make of it and find more inspiration.
Right now this is an idea sprung only from my head. I want more eyes on it
to see where it can be improved.

Sorry if the lack of real structured planning disappoints,
//Erik Nyström


Den sön 1 mars 2020 kl 20:42 skrev Joe Finn <notifications@github.com>:

**Comment by Joe118** [comment]
Thanks Erik for your lengthy reply. It's about what I expected, actually better than my own reply would be for my projects ;) I'll send you some more questions about features after I play with Viking.Pipeline.
